[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_CONTRACT_ADDRESS = "8c34b5c05fe7ae32e5de68635a08d670c9a4ff5049ab2c2f76ffc95597b9082e"
  VITE_MIN_NET_WORTH_THRESHOLD = "1000000"
  VITE_MIN_INCOME_THRESHOLD = "200000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/managed/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
